name: DebuggingCommands
version: 1.0
author: FluffyBear
main: me.fluffybear.debuggingcommands.DebuggingCommands
description: Used to find random stuff

commands:
  enchantfinder:
    description: Find all enchants on server
    usage: /<command>
    permission: op
  printmeta:
    description: Get item metadata
    usage: /<command>
    permission: op
  copymeta:
    description: Copies item metadata
    usage: /<command>
    permission: op
  pastemeta:
    description: Pastes stored item metadata
    usage: /<command>
    permission: op
  bsaddinfo:
    description: Adds block data (Slimefun)
    usage: /<command>
    permission: op
  finditem:
    description: Finds an item in all player inventories
    usage: /<command>
    permission: op
